# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nb2script": "00_core.ipynb",
         "clean": "01_utils.ipynb",
         "extract_minibatch": "01_utils.ipynb",
         "get_files_dir": "01_utils.ipynb",
         "get_name_training": "01_utils.ipynb",
         "get_id_training": "01_utils.ipynb",
         "get_files_pattern": "01_utils.ipynb",
         "to_byte_tensor": "01_utils.ipynb",
         "to_float_tensor": "01_utils.ipynb",
         "normalize_tan": "01_utils.ipynb",
         "decode_from_tan": "01_utils.ipynb",
         "loader": "01_utils.ipynb",
         "show_img_from_tensor": "01_utils.ipynb",
         "gradient_flow": "01_utils.ipynb",
         "viz_grad_flow": "01_utils.ipynb",
         "activation_flow": "01_utils.ipynb",
         "viz_activation_flow": "01_utils.ipynb",
         "OutputTrainingWidget": "01_utils.ipynb",
         "get_tb_logdir": "01_utils.ipynb",
         "get_identity_training": "01_utils.ipynb",
         "get_tb_writer": "01_utils.ipynb",
         "annealer": "02_training.ipynb",
         "sched_cos": "02_training.ipynb",
         "sched_lin": "02_training.ipynb",
         "sched_no": "02_training.ipynb",
         "SlowStartCyle": "02_training.ipynb",
         "FlatCyle": "02_training.ipynb",
         "OneCyle": "02_training.ipynb",
         "LRFinder": "02_training.ipynb",
         "LinearLR": "02_training.ipynb",
         "ExponentialLR": "02_training.ipynb",
         "StateCacher": "02_training.ipynb",
         "lr_finder": "02_training.ipynb",
         "AdaptiveConcatPool2d": "03_layers.ipynb",
         "CircularPad2d": "03_layers.ipynb",
         "init_cnn": "03_layers.ipynb",
         "generate_gaussian_points": "03_layers.ipynb",
         "generate_gaussian_intervals": "03_layers.ipynb",
         "OTGauss": "03_layers.ipynb"}

modules = ["core.py",
           "utils.py",
           "training.py",
           "layers.py"]

doc_url = "https://tchambon.github.io/tcdeeptools/"

git_url = "https://github.com/tchambon/tcdeeptools/tree/master/"

def custom_doc_links(name): return None
