# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nb2script": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tchambon.github.io/tcdeeptools/"

git_url = "https://github.com/tchambon/tcdeeptools/tree/master/"

def custom_doc_links(name): return None
