# AUTOGENERATED! DO NOT EDIT! File to edit: 03_layers.ipynb (unless otherwise specified).

__all__ = ['AdaptiveConcatPool2d']

# Cell
import torch
from torch import nn

# Cell

#From fastai library
class AdaptiveConcatPool2d(torch.nn.Module):
    "Layer that concats `AdaptiveAvgPool2d` and `AdaptiveMaxPool2d`."
    def __init__(self, sz = None):
        "Output will be 2*sz or 2 if sz is None"
        super().__init__()
        self.output_size = sz or 1
        self.ap = nn.AdaptiveAvgPool2d(self.output_size)
        self.mp = nn.AdaptiveMaxPool2d(self.output_size)

    def forward(self, x): return torch.cat([self.mp(x), self.ap(x)], 1)